version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cashflow
      POSTGRES_PASSWORD: cashflow
      POSTGRES_DB: cashflow
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cashflow -d cashflow"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]

  frontend:
    build: ./frontend
    depends_on: [backend]
    ports: ["5173:5173"]
    environment:
      VITE_API: http://localhost:8000

volumes:
  pgdata:
